# version: "3.9"

# services:
#   web:
#     build: .
#     container_name: django-app
#     command: python manage.py runserver 0.0.0.0:8000
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#     env_file:
#       - .env


services:
  web:
    image: joan30122001/jira:latest
    container_name: django-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TESTLINK_URL=http://testlink
    depends_on:
      - testlink
    restart: unless-stopped

  testlinkdb:
    image: mariadb:10.11
    container_name: testlink-db
    environment:
      - MARIADB_ROOT_PASSWORD=${TESTLINK_DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${TESTLINK_DB_NAME}
      - MARIADB_USER=${TESTLINK_DB_USER}
      - MARIADB_PASSWORD=${TESTLINK_DB_PASSWORD}
    volumes:
      - testlink_db_data:/var/lib/mysql
    restart: unless-stopped

  testlink:
    image: gigashiro/testlink:1.0.0
    container_name: testlink
    ports:
      - "8085:80"
    environment:
      - DB_HOST=testlinkdb
      - DB_NAME=${TESTLINK_DB_NAME}
      - DB_USER=${TESTLINK_DB_USER}
      - DB_PASS=${TESTLINK_DB_PASSWORD}
    depends_on:
      - testlinkdb
    volumes:
      - testlink_data:/var/testlink
    restart: unless-stopped

volumes:
  testlink_db_data:
  testlink_data:
